use crate::protocol::{ExecStatus, Job};
use serde_json::json;
use super::HandlerResult;

pub async fn handle_human_approval(job: &Job) -> HandlerResult {
    let prompt = match job.payload.get("prompt").and_then(|v| v.as_str()) {
        Some(p) => p,
        None => return (
            ExecStatus::Error,
            job.r#type.clone(),
            None,
            Some("MISSING_PROMPT".to_string()),
            Some("Missing 'prompt' in payload".to_string())
        ),
    };

    let default_options = json!(["Approve", "Reject"]);
    let options = job.payload.get("options").unwrap_or(&default_options);
    
    let response = job.payload.get("response").and_then(|v| v.as_str()).unwrap_or("Approve");

    let output = json!({
        "prompt": prompt,
        "options": options,
        "status": "completed",
        "decision": response,
        "comment": "Auto-generated by worker stub"
    });

    (ExecStatus::Success, job.r#type.clone(), Some(output), None, None)
}
